name = "TACLEX ML";
author = "TACLEX Community Project";
version = "1.0.0";
url = "https://steamcommunity.com/sharedfiles/filedetails/?id=XXXXXXXXX";
logo = "taclex_icon.paa";
logoOver = "taclex_icon.paa";
picture = "taclex_icon.paa";
tooltip = "TACLEX ML";
tooltipOwned = "TACLEX ML - AI Mission Generation";
overview = "Generate real Arma 3 missions from natural language. Connect with 8 LLM providers (Groq, OpenAI, OpenRouter, DeepSeek, Cerebras, Fireworks, Together, Ollama). Open Source, MIT.";
hideName = 0;
hidePicture = 0;